project:
  type: website
  output-dir: docs


website:
  title: "Digital Earths global hackathon 2025"
  navbar:
    background: "#627797"
    left:
      - href: hosting/meeting-dates-and-times.md
    right:
      - href: https://www.dkrz.de/de/about/kontakt/impressum
        text: legal
      - href: https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement
        text: privacy
  sidebar:
    search: true
    contents: auto



format:
  html:
    theme: lumen
    toc: true
